name: tasaciones_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^2.3.12 
  provider: ^6.0.3
  logger: ^1.1.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  dio: ^4.0.6
  blurry_modal_progress_hud: ^1.0.3
  flutter_spinkit: ^5.1.0
  advanced_datatable: 
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  email_validator: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
   - assets/img/
 
