name: tasaciones_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  advanced_datatable: null
  blurry_modal_progress_hud: ^1.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_search: ^5.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_pw_validator: ^1.4.2
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  line_icons: ^2.0.1
  logger: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  qr_code_scanner: null
  shared_preferences: ^2.0.15
  stacked: ^2.3.12
  themify_flutter: ^1.0.0
  uni_links: ^0.5.1
  money_formatter: ^0.0.3
  flutter_masked_text: ^0.8.0
  photo_view: ^0.14.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
